simulating a fail in workflow

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -8,9 +8,14 @@ jobs:
     steps: 
     - name: echo the date
       run: echo "The current time and date is $(date)"
+    - name: Simulate a fail
+      run: exit 1
     - name: echo the current branch
       run: echo ${{ github.ref_name }}
       # $ {{}} github action. compiler reads this syntax and replaces it to github branch name. this is a github action 
+
+
+    # failures will cause subsequent steps to fail/not do
 
 
 
